export const users = [
  {
    id: "1",
    name: "Rogério",
    email: "rogerio@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "2",
    name: "Marcelo",
    email: "marcelo@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "3",
    name: "Rodrigo",
    email: "rodrigo@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "4",
    name: "Frederico",
    email: "frederico@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "5",
    name: "Ana Rosa",
    email: "anarosa@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "6",
    name: "Clarisse",
    email: "clarisse@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "7",
    name: "Rodrigo",
    email: "rodrigo@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "8",
    name: "Frederico",
    email: "frederico@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "9",
    name: "Ana Rosa",
    email: "ana@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "10",
    name: "Clarisse",
    email: "clarisse@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "11",
    name: "Frederico",
    email: "fred@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "12",
    name: "Ana Rosa",
    email: "rosa@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
  {
    id: "13",
    name: "Clarisse",
    email: "cla@gmail.com",
    imagem: require("../../assets/images/casa.jpg"),
  },
];
